### ISSUE TITLE
Broken symbols Windows 10 16251.1002

### ISSUE THREAD

**Issue by pantosha** [sindresorhus/log-symbols#11]
Symbols isn't displayed correctly in cmd or powershell.

**OS:** Windows 10 16251.1002
**Codepage:** 866 and 65001 (https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx)
**Fonts:** Consolas, Source Code Pro

![screenshot](https://user-images.githubusercontent.com/1799798/29685536-7f8d97e8-891e-11e7-9284-c6794c212895.png)

**Comment by sindresorhus** [comment]
// @gucong3000

**Comment by gucong3000** [comment]
When I set the font to `Consolas`, I also reproduce the problem.
@pantosha Have you tried setting up other fonts?

**Comment by gucong3000** [comment]
@sindresorhus I looked up some information. There is no way to get the font that the user is currently using

**Comment by pantosha** [comment]
@gucong3000 , 
I tried several fonts.
# Results

## Consolas
Square with question mark inside:
![Consolas font](https://user-images.githubusercontent.com/1799798/29706312-272abe70-898a-11e7-918e-c228869be59d.png)

## Lucida Console
Empty Square.
![Lucida Console](https://user-images.githubusercontent.com/1799798/29706435-846e9e80-898a-11e7-98b9-345eae1025f9.png)

## Raster fonts
Question mark.
![Raster fonts](https://user-images.githubusercontent.com/1799798/29706464-98c8ed36-898a-11e7-8d8f-f9234f1fa874.png)

## SimSun-ExtB
All work as expected.
![image](https://user-images.githubusercontent.com/1799798/29706550-d76d8d4e-898a-11e7-8826-6d6a2a90bc0c.png)

**Comment by gucong3000** [comment]
I found that in a Western-language version of Windows, emoji is not displayed under the default configuration.

**Comment by pantosha** [comment]
@gucong3000, my default codepage is [CP866](https://en.wikipedia.org/wiki/Code_page_866), and I also tried [CP65001](https://en.wikipedia.org/wiki/Code_page_65001). Symbols are printed correctly only for SimSun-ExtB font.

**Comment by kevva** [comment]
Should be fixed in https://github.com/sindresorhus/log-symbols/commit/fb6e64f6da30184f9046717a66e3f056577f6dcd using the fallbacks.
