### ISSUE TITLE
Icons not showing up in Cmder for Windows

### ISSUE THREAD

**Issue by Sawtaytoes** [sindresorhus/log-symbols#17]
Per this issue in another repo, I'm not able to get the icons to load in Windows while using Cmder in cygwin mode:
https://github.com/SimenB/stylint-stylish/issues/100#issuecomment-375207636

**Comment by sindresorhus** [comment]
What does `node -p "process.env.TERM"` give you when run in Cmder?

**Comment by Sawtaytoes** [comment]
Ah, looks like this machine's running `cygwin`, not cmd. I'll update the title.

**Comment by sindresorhus** [comment]
`cygwin` is not officially supported by Node.js, so you're on your own. I'm not going to add any workarounds for `cygwin`.
