### ISSUE TITLE
symbols are glitching in Ubuntu

### ISSUE THREAD

**Issue by joielee09** [sindresorhus/log-symbols#29]
Hello, I found symbols glitching in Ubuntu Server 20.04 LTS (HVM) as follows.

Step to Reproduce: 
I followed instructions in [npm page](https://www.npmjs.com/package/log-symbols)

```
// index.js
import logSymbols from 'log-symbols';

console.log(logSymbols.info, "info");
console.log(logSymbols.success, "success");
console.log(logSymbols.warning, "warning");
console.log(logSymbols.error, "error");
```
and got this as a result.

![image](https://user-images.githubusercontent.com/67178982/127193400-449414a1-f065-4f0d-bd36-fe0977bcc130.png)

Versions:
"log-symbols": "^5.0.0"
OS: Ubuntu Server 20.04 LTS (HVM)
node: v14.17.2

I looked up issues and PRs but not found a similar issue.
If this is a known problem let me know. Thank you in advance.

**Comment by sindresorhus** [comment]
You'll need to report this to the Ubuntu project. That looks like a rendering bug which has nothing to do with this package.
