### ISSUE TITLE
precompute chalk 

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/log-symbols#30]
By replacing this chalk:
https://github.com/sindresorhus/log-symbols/blob/6aea9853e1fb85a437f868d0ef400ce122c08c1d/index.js#L4-L16

... with precomputed values:
```js
const main = {
  info: '\x1B[34mℹ\x1B[39m',
  success: '\x1B[32m✔\x1B[39m',
  warning: '\x1B[33m⚠\x1B[39m',
  error: '\x1B[31m✖\x1B[39m'
};

const fallback = {
  info: '\x1B[34mi\x1B[39m',
  success: '\x1B[32m√\x1B[39m',
  warning: '\x1B[33m‼\x1B[39m',
  error: '\x1B[31m×\x1B[39m'
};
```

Then it's possible to minimize the package size/JIT by a lot... seems like a worthy tradeoff for readability?

The only dep you would need would be: is-unicode-supported
https://npmgraph.js.org/?q=log-symbols

Another option is to have chalk as a dev dependency and generate them before publishing

**Comment by sindresorhus** [comment]
I'm not totally against it, but it's not as beneficial as you think. Most CLI's will have Chalk somewhere in the dependency tree anyway. You'll also need https://github.com/chalk/supports-color.

**Comment by jimmywarting** [comment]
ahh, so chalk also checks if color is supported, if not then it's just symbols?

**Comment by sindresorhus** [comment]
> ahh, so chalk also checks if color is supported, if not then it's just plain symbols?

Yes

> i found some ppl using other cli tools other than Chalk...

I'm sure you *can* find that, but the majority use Chalk.

**Comment by NickKaramoff** [comment]
@jimmywarting you can use [nanosymbols](https://www.npmjs.com/package/nanosymbols). This is a fully compatible port of this package, but using a more lightweight package for colour support — `picocolors`!

**Comment by sindresorhus** [comment]
> but using a more lightweight package for colour support — picocolors!

https://www.reddit.com/r/javascript/comments/r5ghue/chalk_5_is_out_color_your_terminal_output_with/hmrrewu/?context=3

**Comment by sindresorhus** [comment]
Because of Chalk v5 improvements, the install size is now less than half: https://packagephobia.com/result?p=log-symbols@5.1.0
