### ISSUE TITLE
Unequal width on CI

### ISSUE THREAD

**Issue by gucong3000** [sindresorhus/log-symbols#6]
https://ci.appveyor.com/project/gucong3000/log-symbols/build/1.0.2/job/bohx8aujk836fm07
https://travis-ci.org/sindresorhus/log-symbols/jobs/159114069
https://circleci.com/gh/gucong3000/log-symbols/1
![image](https://user-images.githubusercontent.com/1171691/28306518-25a11c46-6bd2-11e7-95c3-c46976e20c61.png)
![image](https://user-images.githubusercontent.com/1171691/28306523-2e3d5284-6bd2-11e7-9207-19f1591ad050.png)
![image](https://user-images.githubusercontent.com/1171691/28307187-a458c53c-6bd4-11e7-825e-82866d917bfb.png)

`info` is wider than the others.

**Comment by sindresorhus** [comment]
The width is unfortunately system-dependent. Looks better on macOS for example: <img width="108" alt="screen shot 2017-07-18 at 11 29 19" src="https://user-images.githubusercontent.com/170270/28310305-5e23cc24-6bac-11e7-9ae2-e75ac0800848.png">

**Comment by gucong3000** [comment]
Windows 10.0.15063
Chrome 59.0.3071.115

**Comment by sindresorhus** [comment]
Yes, the screenshot is from Chrome on macOS.

**Comment by sindresorhus** [comment]
Closing as there's nothing we can do about this. It's the OSes that decides how to render different characters.
